### ISSUE TITLE
NoMethodError on line 7 of ./helpers/render_partial.rb: undefined method `helpers' for main:Object

### ISSUE THREAD

**Issue by ninjasort** [adamstac/sinatra-bootstrap#10]

**Comment by ptrikutam** [comment]
I'm getting the same issue. Did you ever figure this out?

**Comment by ninjasort** [comment]
It should work now.. try re-cloning the repo and running `bundle install` then `rake s`

**Comment by ptrikutam** [comment]
Actually, I'm able to run the project just fine-- it's running `compass watch` that causes the error for me.

Here's the full stack trace:

```
=> $ compass watch --trace
NoMethodError on line ["7"] of /Users/pavan/Development/test/sinatra-bootstrap/helpers/render_partial.rb: undefined method `helpers' for main:Object
  /Users/pavan/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/pavan/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/pavan/Development/test/sinatra-bootstrap/app.rb:6:in `<class:SinatraBootstrap>'
  /Users/pavan/Development/test/sinatra-bootstrap/app.rb:5:in `<top (required)>'
  /Users/pavan/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/pavan/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require'
  /Users/pavan/Development/test/sinatra-bootstrap/config.rb:1:in `get_binding'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:24:in `eval'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:24:in `parse_string'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:15:in `block in _parse'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:14:in `open'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:14:in `_parse'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/inheritance.rb:204:in `with_defaults'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:6:in `new_from_file'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:42:in `configuration_for'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:97:in `add_project_configuration'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/project_base.rb:31:in `add_project_configuration'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/project_base.rb:25:in `configure!'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/project_base.rb:15:in `initialize'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/update_project.rb:37:in `initialize'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/bin/compass:44:in `call'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/bin/compass:23:in `load'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/bin/compass:23:in `<main>'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `eval'
  /Users/pavan/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `<main>'
```

Any thoughts? In the meantime I'm just getting around it by commenting out the `helpers RenderPartial` line in `RenderPartial.rb`. I haven't started digging into it in depth and seeing if I can still render partial layouts, but does commenting out that line cause any significant problems?

**Comment by ptrikutam** [comment]
OK, upon reading [this page](http://www.sinatrarb.com/extensions.html) (still new to Sinatra) I'm realizing that line I removed might be necessary. Strange thing is, when I move the `helpers RenderPartial` outside of the `RenderPartial.rb` and to the `app.rb` file (just below the `require './helpers/render_partial'` line), `compass watch` works just fine. Also, `rake s` still works. 

Maybe this has to do with the ruby version I'm using?

**Comment by ninjasort** [comment]
I think the `require './helpers/render_partial.rb'` inside the `SinatraBootstrap` class wasn't finding the `Sinatra::Base` I put the require at the top and moved `helpers RenderPartial` inside the `SinatraBootstrap` class. At that point the `helpers` is defined from `Sinatra::Base`. Shouldn't have to do with the version of Ruby.
